Repository alexander-sidorov/m-pt1-58-22, pull requests merged in 2022-12, with the labels that each got.

#13 maksim_lamaka
  hw/maksim_lamaka/__init__.py
  hw/maksim_lamaka/lesson04/__init__.py
  hw/maksim_lamaka/lesson04/lecture.py
  hw/maksim_lamaka/lesson04/lecture_test.py
Labels: pr:ready-for-merge

#6 karman
  hw/mikita_karmanaw/__init__.py
  hw/mikita_karmanaw/lesson04/__init__.py
  hw/mikita_karmanaw/lesson04/lecture.py
  hw/mikita_karmanaw/lesson04/lecture_test.py
Labels: pr:ready-for-merge

#32 Mikhailiuk Dmitry
  hw/dmitry_mihkailiuk/lesson05/__init__.py
  hw/dmitry_mihkailiuk/lesson05/stdtypes_test.py
  hw/dmitry_mihkailiuk/lesson06/__init__.py
  hw/dmitry_mihkailiuk/lesson06/tasks.py
  hw/dmitry_mihkailiuk/lesson06/tasks_test.py
Labels: pr:ready-for-review

#3 создана папка и добавлен в неё файл
  hw/andrei_karpuk/__init__.py
  hw/andrei_karpuk/lesson04/__init__.py
  hw/andrei_karpuk/lesson04/lecture.py
  hw/andrei_karpuk/lesson04/lecture_test.py
Labels: pr:need-work

#40 Vladislav yurenya 06 Dz
  hw/vladislav_yurenya/lesson06/__init__.py
  hw/vladislav_yurenya/lesson06/tasks.py
  hw/vladislav_yurenya/lesson06/tasks_test.py
Labels: pr:ready-for-review

#44 Vadim zharski 05 06
  hw/vadim_zharski/lesson05/__init__.py
  hw/vadim_zharski/lesson05/stdtypes_test.py
  hw/vadim_zharski/lesson06/__init__.py
  hw/vadim_zharski/lesson06/tasks.py
  hw/vadim_zharski/lesson06/tasks_test.py
Labels: pr:ready-for-review

#49 lesson09
  hw/mikita_karmanaw/lesson09/__init__.py
  hw/mikita_karmanaw/lesson09/tasks.py
  hw/mikita_karmanaw/lesson09/tasks_test.py
Labels: pr:ready-for-review

#56 Dmitry Mikhailiuk: HW 09
  hw/dmitry_mihkailiuk/lesson09/__init__.py
  hw/dmitry_mihkailiuk/lesson09/tasks.py
  hw/dmitry_mihkailiuk/lesson09/tasks_test.py
Labels: pr:ready-for-review

#45 lesson5 v1.0
  hw/eugene_vavilov/lesson05/__init__.py
  hw/eugene_vavilov/lesson05/stdtypes_test.py
Labels: pr:ready-for-review

#52 Vavilov lesson 6
  hw/eugene_vavilov/lesson06/__init__.py
  hw/eugene_vavilov/lesson06/tasks.py
  hw/eugene_vavilov/lesson06/tasks_test.py
Labels: pr:ready-for-review

#62 Vladislav Yurenya Lesson 10
  hw/vladislav_yurenya/lesson10/__init__.py
  hw/vladislav_yurenya/lesson10/lesson.py
  hw/vladislav_yurenya/lesson10/lesson_test.py
Labels: pr:ready-for-review

#55 homework lesson5 and lesson6 + tests
  hw/andrei_karpuk/lesson05/stdtypes_test.py
  hw/andrei_karpuk/lesson06/tasks.py
  hw/andrei_karpuk/lesson06/tasks_test.py
Labels: pr:ready-for-review

#54 Maksim lamaka hw_lesson05
  hw/maksim_lamaka/lesson05/__init__.py
  hw/maksim_lamaka/lesson05/stdtypes_test.py
Labels: pr:ready-for-review, pr:need-work

#46 Lesson5 hw Maksim_Baranau
  hw/maksim_baranau/lesson05/__init__.py
  hw/maksim_baranau/lesson05/stdypes_test.py
Labels: pr:ready-for-review

#71 Vadim Zharski lesson 10
  hw/vadim_zharski/lesson10/__init__.py
  hw/vadim_zharski/lesson10/lesson.py
  hw/vadim_zharski/lesson10/lesson_test.py
Labels: pr:ready-for-review

#85 igor_maksimov_lesson 09
  hw/igor_maksimov/lesson09/__init__.py
  hw/igor_maksimov/lesson09/tasks.py
  hw/igor_maksimov/lesson09/tasks_test.py
Labels: pr:ready-for-review

#59 Mikita Karmanaw Lesson 10-11
  hw/mikita_karmanaw/lesson10/__init__.py
  hw/mikita_karmanaw/lesson10/lesson.py
  hw/mikita_karmanaw/lesson10/lesson_test.py
Labels: pr:ready-for-review

#61 Maksim lamaka lesson 11
  hw/maksim_lamaka/lesson10/__init__.py
  hw/maksim_lamaka/lesson10/lesson.py
  hw/maksim_lamaka/lesson10/lesson_test.py
Labels: pr:ready-for-review, pr:need-work

#92 Dmitry-Mikhailiuk-lisson11
  hw/dmitry_mihkailiuk/lesson10/lesson.py
  hw/dmitry_mihkailiuk/lesson10/lesson_test.py
Labels: pr:ready-for-review

#94 vadim-zharski-lesson-10
  hw/vadim_zharski/lesson10/lesson.py
  hw/vadim_zharski/lesson10/lesson_test.py
Labels: pr:ready-for-review

#114 eugene-vavilov-lesson-09
  hw/eugene_vavilov/lesson09/__init__.py
  hw/eugene_vavilov/lesson09/task.py
  hw/eugene_vavilov/lesson09/task_test.py
Labels: fyi

#112 alexey-tuyhai-lesson09
  hw/alexey_tyuhai/lesson09/__init__.py
  hw/alexey_tyuhai/lesson09/tasks.py
  hw/alexey_tyuhai/lesson09/tasks_test.py
Labels: fyi

#115 Lesson9 Maksim_Baranau
  hw/maksim_baranau/lesson09/__init__.py
  hw/maksim_baranau/lesson09/tasks.py
  hw/maksim_baranau/lesson09/tasks_test.py
Labels: pr:ready-for-review

#120 Vladislav Yurenya fixed coverage lesson09
  hw/vladislav_yurenya/lesson09/tasks.py
  hw/vladislav_yurenya/lesson09/tasks_test.py
Labels: pr:ready-for-review

#106 Mikita Karmanaw Lesson 12
  hw/mikita_karmanaw/lesson12/__init__.py
  hw/mikita_karmanaw/lesson12/lesson.py
  hw/mikita_karmanaw/lesson12/lesson_test.py
Labels: pr:ready-for-review
